"""Integration test: Validate legitimate LLM-generated queries pass validation.

This is the INTEGRATION CHECKPOINT (Task 8) that ensures:
1. All legitimate queries from Story 1.5 pass validation
2. Validation doesn't block legitimate business queries
3. The full flow (sanitization → LLM → validation) works end-to-end

Source: Story 1.6, Task 8
"""

from app.services.validation_service import validate_sql


def test_legitimate_queries_pass_validation():
    """
    Test that validation ALLOWS all 4 mandatory LLM-generated queries.

    These are the actual SQL patterns generated by the LLM in Story 1.5 Task 7.
    If any fail, the validation logic (not LLM prompt) must be adjusted.
    """
    test_cases = [
        (
            "Recent hires",
            "SELECT * FROM employees WHERE hire_date >= CURRENT_DATE - INTERVAL '6 months'"
        ),
        (
            "Engineering high earners",
            "SELECT * FROM employees WHERE department = 'Engineering' AND salary_usd > 120000"
        ),
        (
            "Parental leave",
            "SELECT * FROM employees WHERE leave_type = 'Parental Leave'"
        ),
        (
            "John Doe reports",
            "SELECT * FROM employees WHERE manager_name = 'John Doe'"
        ),
    ]

    print("\n" + "=" * 70)
    print("INTEGRATION CHECKPOINT: Testing Legitimate Query Validation")
    print("=" * 70 + "\n")

    all_passed = True
    for name, sql in test_cases:
        try:
            validate_sql(sql, nl_query=name)
            print(f"[PASS] {name:30} validation passed")
        except ValueError as e:
            print(f"[FAIL] {name:30} FAILED - {e}")
            print(f"  SQL: {sql}")
            all_passed = False

    print("\n" + "=" * 70)
    if all_passed:
        print("[SUCCESS] All legitimate queries pass validation")
        print("=" * 70 + "\n")
    else:
        print("[ERROR] CHECKPOINT FAILED: Some legitimate queries blocked")
        print("=" * 70 + "\n")
        raise Exception("Validation blocked legitimate queries - adjust validation logic")


if __name__ == "__main__":
    test_legitimate_queries_pass_validation()
